### PR TITLE
Dependency manage

### PR DESCRIPTION
**Pull request by lucyawrey**

### CODE REVIEW

**Comment by laura-wenning** [comment]
Getting this warning when running the project:
image

**Comment by lucyawrey** [comment]
> Getting this warning when running the project: image

Running or installing?

**Comment by laura-wenning** [comment]
Running the project. I don't appear to have any issues with rendering things, but that error is flooding my logs

**Comment by laura-wenning** [comment]
Since the error is coming from apollo-server-micro and that will take some work to remove, this is good to go for now.

**Review by laura-wenning — APPROVED** [review]

**Pull request merged**
